config/routes.rb
TimePulse::Application.routes.draw do

  resources :invoices
  resources :bills
  resources :groups
  resources :permissions
  resources :work_units, :except => :index
  resources :clients
  resources :projects do
    resource :github_pull, :controller => 'github_pull', :only => [:create]
    resource :pivotal_pull, :controller => 'pivotal_pull', :only => [:create]
  end
  resources :rates, :only => :update

  resources :project_reports
  resources :invoice_reports, :only => :show

  resource :github, :only => [:create], :controller => 'github'
  resource :pivotal, :only => [:create], :controller => 'pivotal'
  resource :user_preferences, :only => [ :edit, :update ]

  # TODO: Reenable these once LAz is working
  # match '/forbid' => 'permissions#destroy', :as => :forbid, :via => delete
  # match '/permit' => 'permissions#create', :as => :permit, :via => post
  # match '/ungroup_user' => 'groups_users#destroy', :as => :ungroup_user, :via => delete
  # match '/group_user' => 'groups_users#create', :as => :group_user, :via => post

  devise_for :users, :controllers => {:registrations => 'users' }
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy", :as => :logout
    get "/users/new" => "users#new", :as => :new_user
    get "/users" => "users#index", :as => :users
    get "/users/:id" => "users#show", :as => :user
    get "/users/:id/edit" => "users#edit", :as => :edit_user
    patch "/users/:id" => "users#update", :as => :update_user
  end
  match '/fix_work_unit/:id' => 'work_unit_fixer#create', :as => :fix_work_unit, :via => :post
  match '/set_current_project/:id' => 'current_project#create', :as => :set_current_project, :via => :post
  match '/clock_in_on/:id' => 'clock_time#create', :as => :clock_in, :via => :post
  match '/clock_out' => 'clock_time#destroy', :as => :clock_out, :via => :delete

  root :to => 'home#index'

end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id               :integer(4)      not null, primary key
#  client_id        :integer(4)
#  notes            :text
#  created_at       :datetime
#  updated_at       :datetime
#  due_on           :date
#  paid_on          :date
#  reference_number :string(255)
#

class Invoice < ActiveRecord::Base
  include I18n::Alchemy
  belongs_to :client
  has_many :work_units
  has_many :invoice_items, :autosave => true, :dependent => :destroy

  validates_presence_of :client_id

  scope :overdue, lambda { where("paid_on IS NULL AND due_on < ? ", Date.today) }

  scope :unpaid,  lambda { where("paid_on IS NULL") }

  scope :paid, lambda { where("paid_on IS NOT NULL") }

  accepts_nested_attributes_for :work_units, :reject_if => :all_blank, :allow_destroy => :false

  before_save :generate_invoice_items, :if => :new_record?
  before_destroy :dissociate_work_units

  # TODO: Reimplement this with i18n
  # attr_human_name :reference_number => 'Ref #'

  def hours
    work_units.sum(:hours)
  end

  def paid?
    !paid_on.nil?
  end

  def total
    total = 0
    self.invoice_items.each do |item|
      total += item.total
    end
    total
  end

  def dissociate_work_units
    self.work_units.each do |wu|
      wu.invoice = nil
      wu.save
    end
  end

  private

  def generate_invoice_items
    client_project = Project.where(:client_id => client.id, :parent_id => Project.root.id).first
    if client_project.nil?
      errors.add :invoice_items, "This client has no projects."
      return false
    end

    items = {}
    rates = client_project.rates
    rates.each do |rate|
      items[rate.id] = { :name => rate.name, :hours => 0.0, :amount => rate.amount.to_f, :total => 0.0 }
    end

    self.work_units.each do |wu|
      user_rate = wu.user.rate_for(client_project)
      if !user_rate.blank? && item = items[user_rate.id]
        item[:hours] += wu.hours
        item[:total] += wu.hours * item[:amount]
      else
        errors.add :invoice_items, "There is no rate assigned to #{wu.user.name} for this client."
        return false
      end
    end

    items.values.each do |item|
      invoice_item = InvoiceItem.create
      invoice_item.name = item[:name]
      invoice_item.hours = item[:hours]
      invoice_item.amount = item[:amount]
      invoice_item.total = item[:total]
      invoice_items << invoice_item
    end
  end


end

app/controllers/invoices_controller.rb
require 'work_unit_tools'

class InvoicesController < ApplicationController
  before_filter :find_invoice, :only => [ :show, :edit, :update, :destroy ]
  before_filter :require_admin!

  include WorkUnitTools

  # GET /invoices
  def index
    @unpaid_invoices = UnpaidInvoiceQuery.new.find_for_page(params[:page])
    @paid_invoices = PaidInvoiceQuery.new.find_for_page(params[:page])
  end

  # GET /invoices/1
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new(:due_on => Date.today + 21.days)
    @clients = Client.all.order('abbreviation asc')
    if params[:client_id]
      @client = find_user(Client, params[:client_id])
      @invoice.client = @client
      @work_units = WorkUnit.for_client(@client).order(stop_time: :asc).with_hours.billable.uninvoiced.flatten.uniq
    end
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  def create
    @invoice = Invoice.new(invoice_params)
    add_work_units(@invoice, params[:invoice][:work_unit_ids])
    if @invoice.save
      flash[:notice] = 'Invoice was successfully created.'
      redirect_to(@invoice)
    else
      flash[:error] = "Could not save invoice.  errors: #{error_list}"
      params[:client_id] = @invoice.client.id if @invoice.client
      render :action => "new"
    end
  end

  # PUT /invoices/1
  def update
    if @invoice.update_attributes(invoice_params)
      flash[:notice] = 'Invoice was successfully updated.'
      redirect_to(@invoice)
    else
      render :action => "edit"
    end
  end

  # DELETE /invoices/1
  def destroy
    @invoice.destroy
    redirect_to(invoices_url)
  end

  private

  def find_invoice
    @invoice = Invoice.find(params[:id])
    raise ArgumentError, 'Invalid invoice id provided' unless @invoice
  end

  # def find_client
  #   @client = Client.find_by_id(params[:client_id])
  #   unless @client
  #     flash[:error] = "Could not find the specified client"
  #     redirect_to :back
  #   end
  # end

  def error_list
    @invoice.errors.map{ |error, message| message }.join(', ')
  end

  # def add_work_units
  #   if params[:invoice][:work_unit_ids]
  #     @invoice.work_units = []
  #     params[:invoice][:work_unit_ids].each do |id, bool|
  #       @invoice.work_units << WorkUnit.find(id) if bool == "1"
  #     end
  #   end
  # end

  def invoice_params
    params.require(:invoice)
    .permit(:notes,
      :due_on,
      :paid_on,
      :reference_number,
      :client_id)
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def invoice_client_selector()
    if @client
      select_tag( :client_id, options_for_select(client_selector_array_with_hours, @client.id), { :include_blank => "", :class => "invoice-client-selector" })
    else
      select_tag( :client_id, options_for_select(client_selector_array_with_hours), { :include_blank => "", :class => "invoice-client-selector"  })
    end
  end

  def client_selector_array_with_hours
    @client_array ||= Client.all.to_a.collect{ |c| [
       "#{c.name} - (#{WorkUnit.for_client(c).uninvoiced.completed.billable.sum(:hours)}) ",
       c.id
    ]}
  end

  def invoice_item_footer(items)
    totals = { :hours => 0, :total => 0 }
    items.each do |item|
      totals[:hours] += item.hours
      totals[:total] += item.total
    end
    content_tag(:tfoot) do
      content_tag(:th, 'Total') +
      content_tag(:th, '&nbsp;', nil, false) +
      content_tag(:th, totals[:hours]) +
      content_tag(:th, number_to_currency(totals[:total], :precision => 2))
    end
  end

  def work_unit_hours_td(work_unit, &block)
    rate = work_unit.rate
    attributes = {:class => "hours"}
    if rate
      attributes[:'data-rate-id'] = rate.id
      attributes[:'data-rate-name'] = rate.name
      attributes[:'data-rate-amount'] = rate.amount
    end
    content_tag(:td, attributes, &block)
  end
end

app/views/invoices/_form.html.haml
= form_for(@invoice) do |f|
  = f.error_messages

  / = f.hidden_field :client_id, @invoice.client.id
  %input#invoice_client_id{ :name => "invoice[client_id]", :type => "hidden", :value => @invoice.client.id }
  = labeled_datepicker_field f, :due_on
  = labeled_datepicker_field f, :paid_on
  = f.labeled_input(:notes) do
    = f.text_area(:notes, :size => '60x4')
  = f.labeled_input(:reference_number) do
    = f.text_field(:reference_number)

  - if @work_units
    %input#work_unit_select_all{ :type => 'button', :value => 'select all' }
    %table#totals.listing
      %thead
        %tr
          %th Rate
          %th Work Units
          %th Hours
          %th Total $
      %tbody
        %tr#rate_total
          %td
            Totals
          %td 0
          %td 0.00
          %td 0.00

    %table.listing
      = f.fields_for :work_unit_ids do |wu_form|
        - @work_units.each do |wu|
          = content_tag_for(:tr, wu, :class => (!wu.rate ? 'no-rate' : '')) do
            = work_unit_hours_td(wu) do
              = wu_form.check_box(wu.id, :class => 'work_unit_checkbox')
              = wu_form.label(wu.id, wu.hours, :class => 'hours_count')
            %td= wu.user.login
            %td= wu.notes
            %td.nobr= wu.start_time.try(:to_s, :short_date_and_time)
            %td.nobr= work_unit_stop_time(wu)
            %td.tools.nobr= link_to 'Edit', edit_work_unit_path(wu), class: 'actions edit'

  = f.unlabeled_submit

app/views/invoices/_invoice.html.haml
= content_tag_for :tr, invoice do
  %td= invoice.client.name
  %td= invoice.hours
  %td.date= invoice.created_at.to_s(:date)
  %td.date= invoice.due_on
  %td.date= invoice.paid_on
  %td= invoice.notes
  %td= invoice.reference_number

  %td.tools
    = link_to 'Show', invoice, class: 'actions show'
    = link_to 'Edit', edit_invoice_path(invoice), class: 'actions edit'
    = link_to 'Destroy', invoice, data: { confirm: 'Are you sure?' }, :method => :delete, class: 'actions delete'

app/views/invoices/_invoice_details.html.haml
%hr

%h2 Hours Report
%table.listing
  %tr
    %th Project
    %th Hours
    -# TODO: move some of this logic to a helper, or better yet, to a model method.
    - sanity_sum = 0
    - @invoice.work_units.order(stop_time: :asc).collect{ |wu| wu.project if wu.project.clockable }.compact.uniq.each do |proj|
      - hrs = ProjectWorkQuery.new(@invoice.work_units).find_for_project(proj).sum(:hours)
      - sanity_sum += hrs
      %tr
        %td= proj.name
        %td= hrs
    %tr
      %td
        %b Total
      %td
        %b= sanity_sum

%hr

%h2 Work Unit Details
%table.listing
  %tr
    %th Hours
    %th User
    %th Notes
    %th Start Time
    %th
  - @invoice.work_units.each do |wu|
    = content_tag_for(:tr, wu) do
      %td.hours
        %b= wu.hours
      %td= wu.user.login
      %td= wu.notes
      %td.nobr= wu.start_time.try(:to_s, :short_date_and_time)
      %td.tools.nobr= link_to 'Edit', edit_work_unit_path(wu), class: 'actions edit'

app/views/invoices/_invoice_header.html.haml
%tr
  %th For
  %th Hours
  %th Created
  %th Due
  %th Paid
  %th Notes
  %th Reference number

app/views/invoices/_invoice_items.html.haml
%h2 Invoice Items
%table.listing.invoice-items
  %thead
    %tr
      %th Name
      %th Rate
      %th Total Hours
      %th Total Cost
  = invoice_item_footer @invoice.invoice_items
  %tbody
    - @invoice.invoice_items.each do |item|
      %tr
        %td= item.name
        %td= number_to_currency item.amount, :precision => 2
        %td= item.hours
        %td= number_to_currency item.total, :precision => 2

app/views/invoices/_work_units_info_aux.haml
= content_for :aux do
  = page_block "#{@client.name} Work" do
    %table.listing
      %tr
        %th
        %th Units
        %th Hours
      %tr
        %th Total
        %td= WorkUnit.for_client(@client).completed.count
        %td= WorkUnit.for_client(@client).completed.sum(:hours)
      %tr
        %th Invoiced
        %td= WorkUnit.for_client(@client).completed.invoiced.count
        %td= WorkUnit.for_client(@client).completed.invoiced.sum(:hours)
      %tr
        %th Uninvoiced
        %td= WorkUnit.for_client(@client).completed.uninvoiced.count
        %td= WorkUnit.for_client(@client).completed.uninvoiced.sum(:hours)
      %tr
        %th Shown
        %td= @work_units.count
        %td= number_with_precision(@work_units.inject(0.0){ |sum, wu| sum += wu.hours }, :precision => 2)

app/views/invoices/edit.html.haml
- set_headline "Editing Invoice"

.button-wrap
  = link_to 'Show', @invoice, class: 'button radius'
  = link_to 'Back to List', invoices_path, class: 'button radius'

= render :partial => "form"

= render :partial => 'invoice_details'

app/views/invoices/index.html.haml
- set_headline "Listing Invoices"

.button-wrap
  = link_to 'New Invoice', new_invoice_path, class: 'button radius'

= tabbed_panel do |tp|
  = tp.add_tab("Unpaid") do
    = will_paginate @unpaid_invoices
    %table.listing
      = render :partial => "invoice_header"
      = render :partial => "invoice", :collection => @unpaid_invoices

  = tp.add_tab("Paid") do
    = will_paginate @paid_invoices
    %table.listing
      = render :partial => "invoice_header"
      = render :partial => "invoice", :collection => @paid_invoices

app/views/invoices/new.html.haml
- set_headline "New Invoice"

.button-wrap
  = link_to 'Back to List', invoices_path, class: 'button radius'

= page_block "Invoice Parameters" do
  = form_tag new_invoice_path, :method => 'get' do
    = invoice_client_selector
    = submit_tag "Set Parameters"

- if @client
  = render :partial => 'work_units_info_aux'

  = page_block "Create Invoice" do
    = render :partial => "form"

app/views/invoices/show.html.haml
- set_headline "Invoice for #{@invoice.client.name}"

.button-wrap
  = link_to 'Edit', edit_invoice_path(@invoice), class: 'button radius'
  = link_to 'Back to List', invoices_path, class: 'button radius'
  = link_to 'View Report', invoice_report_path(@invoice), class: 'button radius'
  = link_to 'Print Report', "#", :class => "print-report-button", :"data-print-target" => "print_iframe", class: 'button radius'

%h2 Overview
%table.listing
  %tr
    %th Created:
    %td= @invoice.created_at.to_s(:date)
  %tr
    %th Due:
    %td= @invoice.due_on.try(:to_s, :date)
  %tr
    %th Paid:
    %td= @invoice.paid_on.try(:to_s, :date)
  %tr
    %th Total Hours:
    %td= @invoice.work_units.sum(:hours)
  %tr
    %th Reference #:
    %td= @invoice.reference_number
  %tr
    %th Notes
    %td= @invoice.notes

%hr

= render :partial => 'invoice_items'

%hr

= render :partial => 'invoice_details'

%iframe#print_iframe{:name => "print_iframe", :src => invoice_report_path(@invoice.id)}