config/routes.rb
TimePulse::Application.routes.draw do

  resources :invoices
  resources :bills
  resources :groups
  resources :permissions
  resources :work_units, :except => :index
  resources :clients
  resources :projects do
    resource :github_pull, :controller => 'github_pull', :only => [:create]
    resource :pivotal_pull, :controller => 'pivotal_pull', :only => [:create]
  end
  resources :rates, :only => :update

  resources :project_reports
  resources :invoice_reports, :only => :show

  resource :github, :only => [:create], :controller => 'github'
  resource :pivotal, :only => [:create], :controller => 'pivotal'
  resource :user_preferences, :only => [ :edit, :update ]

  # TODO: Reenable these once LAz is working
  # match '/forbid' => 'permissions#destroy', :as => :forbid, :via => delete
  # match '/permit' => 'permissions#create', :as => :permit, :via => post
  # match '/ungroup_user' => 'groups_users#destroy', :as => :ungroup_user, :via => delete
  # match '/group_user' => 'groups_users#create', :as => :group_user, :via => post

  devise_for :users, :controllers => {:registrations => 'users' }
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy", :as => :logout
    get "/users/new" => "users#new", :as => :new_user
    get "/users" => "users#index", :as => :users
    get "/users/:id" => "users#show", :as => :user
    get "/users/:id/edit" => "users#edit", :as => :edit_user
    patch "/users/:id" => "users#update", :as => :update_user
  end
  match '/fix_work_unit/:id' => 'work_unit_fixer#create', :as => :fix_work_unit, :via => :post
  match '/set_current_project/:id' => 'current_project#create', :as => :set_current_project, :via => :post
  match '/clock_in_on/:id' => 'clock_time#create', :as => :clock_in, :via => :post
  match '/clock_out' => 'clock_time#destroy', :as => :clock_out, :via => :delete

  root :to => 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer(4)      not null, primary key
#  login               :string(255)     not null
#  email               :string(255)     not null
#  current_project_id  :integer(4)
#  name                :string(255)     not null
#  crypted_password    :string(255)     not null
#  password_salt       :string(255)     not null
#  persistence_token   :string(255)     not null
#  single_access_token :string(255)     not null
#  perishable_token    :string(255)     not null
#  login_count         :integer(4)      default(0), not null
#  failed_login_count  :integer(4)      default(0), not null
#  last_request_at     :datetime
#  current_login_at    :datetime
#  last_login_at       :datetime
#  current_login_ip    :string(255)
#  last_login_ip       :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#

class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable

  belongs_to :current_project, :class_name => "Project"
  has_many :work_units
  has_many :bills
  has_many :activities
  has_many :rates_users
  has_many :rates, :through => :rates_users
  has_one  :user_preferences

  validates_presence_of :name, :email

  scope :inactive, lambda { where(inactive: true )  }

  scope :active,   lambda { where(inactive: false)  }

  def reset_current_work_unit
    @cwu = nil
  end

  def current_work_unit
    @cwu ||= work_units.in_progress.first
  end

  def clocked_in?
    reset_current_work_unit
    !current_work_unit.nil?
  end

  def recent_projects
    @wu_list = (WorkUnit.user_work_units(self).most_recent(100))
    @pid_list = @wu_list.collect{ |w| w.project_id }.uniq[0..(self.user_preferences.recent_projects_count-1)]
    Project.find(@pid_list).sort_by{ |proj| @pid_list.index(proj.id) }
  end

  def recent_work_units
    work_units.completed.recent.includes(:project => :client)
  end

  def recent_commits
    activities.git_commits.recent.includes(:project => :client)
  end

  def recent_pivotal_updates
    activities.pivotal_updates.recent.includes(:project => :client)
  end

  def time_on_project(project)
    work_units_for(project).sum(:hours)
  end

  def unbilled_time_on_project(project)
    work_units_for(project).unbilled.sum(:hours)
  end

  def unbillable_time_on_project(project)
    work_units_for(project).unbillable.sum(:hours)
  end

  def completed_work_units_for(project)
    work_units_for(project).completed
  end

  def git_commits_for(project)
    source = project.github_url_source
    source ||= project
    activity_for(source).git_commits
  end

  def pivotal_updates_for(project)
    source = project.pivotal_id_source
    source ||= project
    activity_for(source).pivotal_updates
  end

  def current_project_hours_report
    @cphr ||= hours_report_on(current_project)
  end

  def hours_report_on(project)
    HoursReport.new(project, self)
  end

  def old_admin?
    #groups.include?(Group.admin_group)
  end

  def admin?
    admin
  end

  def activity_for(project)
    ProjectActivityQuery.new(activities).find_for_project(project)
  end

  def work_units_for(project)
    ProjectWorkQuery.new(work_units).find_for_project(project)
  end

  def rate_for(project)
    project = project.parent unless project.is_base_project?
    (project.rates & rates).last
  end

  def active_for_authentication?
    super && !self.inactive?
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(login) = :value OR lower(email) = :value",
                               { :value => login.downcase}]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  skip_before_filter :require_no_authentication
  before_filter :require_admin!, :only => [:index, :new, :create]
  before_filter :get_user_and_authenticate, :only => [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.build_user_preferences

    if @user.save
      flash[:notice] = "Account registered!"
      redirect_to user_path(@user)
    else
      render :action => :new
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    nil_unused_params
    if current_user.admin?
      @user.update(admin_user_params)
    else
      @user.update(user_params)
    end

    if @user.save
      flash[:notice] = "Account updated!"
    end
    render :action => :edit
  end

  def nil_unused_params
    [ :password, :password_confirmation].each do |param|
      if params[:user][param] and params[:user][param].blank?
        params[:user].delete(param)
      end
    end
  end

  private
  def get_user_and_authenticate
    Rails.logger.debug params.inspect
    @user = User.find(params[:id])
    require_owner!(@user)
  end

  def user_params
    params.
    require(:user).
    permit(:login,
      :name,
      :email,
      :password,
      :password_confirmation,
      :github_user,
      :pivotal_name,
      :current_project_id)
  end

  def admin_user_params
    params.
    require(:user).
    permit(:login,
      :name,
      :email,
      :password,
      :password_confirmation,
      :github_user,
      :pivotal_name,
      :admin,
      :inactive,
      :current_project_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_project
    current_user.current_project if logged_in?
  end

  def new_work_unit_for_current_project
    wu = WorkUnit.new
    wu.project = current_project
    wu
  end

end

app/views/users/_info_form.html.haml
= error_messages_for :user
= form_for @user do |f|
  = f.labeled_input :name  if @user.new_record?
  = f.labeled_input :login if @user.new_record?
  = f.labeled_input :email
  = f.labeled_input :github_user
  = f.labeled_input :pivotal_name, :comment => "(unneccesary if name = user's full name on pivotal)"
  = f.labeled_input :password
  = f.labeled_input :password_confirmation
  - if current_user.admin?
    = f.labeled_input :inactive do
      = f.check_box :inactive
    = f.labeled_input :admin do
      = f.check_box :admin
  = f.unlabeled_submit "Submit"

app/views/users/_preferences_form.html.haml
= form_for @user.user_preferences, url: user_preferences_path do |f|
  = f.labeled_input :recent_projects_count
  = f.unlabeled_submit "Submit"

app/views/users/edit.html.haml
- set_headline "Edit Account"
= tabbed_panel do |tp|
  = tp.add_tab("Info") do
    = render :partial => 'info_form'
  - if @user.user_preferences
    = tp.add_tab("Preferences") do
      = render :partial => 'preferences_form'

app/views/users/index.html.haml
- set_headline  "Listing Users"

.button-wrap
  = link_to_if_admin_authorized("New User", new_user_path, class: 'button radius')

%table.listing
  %tr
    %th Name
    %th Email
    %th Current Project
  - @users.each do |user|
    %tr
      %td= link_to_if_owner_authorized(user, user.name, user)
      %td= user.email
      %td= user.current_project.try(:name) || "(none)"
      %td= link_to_if_owner_authorized(user, "Edit", edit_user_path(user), class: 'actions edit') {}

app/views/users/new.html.haml
- set_headline "New User"

.button-wrap
  = link_to 'Back to List', users_path, class: 'button radius'

= render :partial => 'info_form'

app/views/users/show.html.haml
-set_headline "User"
%dl.values
  %dt Name
  %dd= @user.name
  %dt Email
  %dd= @user.email
  %dt Login
  %dd= @user.login
  %dt Github User
  %dd= @user.github_user
  %dt Pivotal Name
  %dd= @user.pivotal_name
%ul
  %li=link_to_if_owner_authorized(@user, "Edit", :action => :edit)
  %li=link_to 'Preferences', edit_user_preferences_path
  %li=link_to_if_owner_authorized(@user, "List", :action => :index)
  %li=link_to("Dashboard", root_path)