config/routes.rb
TimePulse::Application.routes.draw do

  resources :invoices
  resources :bills
  resources :groups
  resources :permissions
  resources :work_units, :except => :index
  resources :clients
  resources :projects do
    resource :github_pull, :controller => 'github_pull', :only => [:create]
    resource :pivotal_pull, :controller => 'pivotal_pull', :only => [:create]
  end
  resources :rates, :only => :update

  resources :project_reports
  resources :invoice_reports, :only => :show

  resource :github, :only => [:create], :controller => 'github'
  resource :pivotal, :only => [:create], :controller => 'pivotal'
  resource :user_preferences, :only => [ :edit, :update ]

  # TODO: Reenable these once LAz is working
  # match '/forbid' => 'permissions#destroy', :as => :forbid, :via => delete
  # match '/permit' => 'permissions#create', :as => :permit, :via => post
  # match '/ungroup_user' => 'groups_users#destroy', :as => :ungroup_user, :via => delete
  # match '/group_user' => 'groups_users#create', :as => :group_user, :via => post

  devise_for :users, :controllers => {:registrations => 'users' }
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy", :as => :logout
    get "/users/new" => "users#new", :as => :new_user
    get "/users" => "users#index", :as => :users
    get "/users/:id" => "users#show", :as => :user
    get "/users/:id/edit" => "users#edit", :as => :edit_user
    patch "/users/:id" => "users#update", :as => :update_user
  end
  match '/fix_work_unit/:id' => 'work_unit_fixer#create', :as => :fix_work_unit, :via => :post
  match '/set_current_project/:id' => 'current_project#create', :as => :set_current_project, :via => :post
  match '/clock_in_on/:id' => 'clock_time#create', :as => :clock_in, :via => :post
  match '/clock_out' => 'clock_time#destroy', :as => :clock_out, :via => :delete

  root :to => 'home#index'

end

app/views/shared/_block.html.haml
- klass = "block #{cssclass}"
- klass += " with_title" if title

%div{ :class => klass.to_s, :id => cssid.to_s  }
  -if title
    = block_title(title, cssid)
    - if defined?(extratitle)
      .extratitle= extratitle
  .block_content
    =body unless body.blank?

app/views/shared/_clock_in_widget.html.haml
- title = "Clock in on #{project.name}"
- form_tag(clock_in_path(:id => project), :method => :post, :title => title, :class => "clock_in") do
  - if defined?(style)  and style == :icon
    = image_submit_tag('icons/clock_in.png', :alt => title)
  - else
    = submit_tag(title)

app/views/shared/_commit_narrow.html.haml
- cache("commit_narrow_#{commit.id}", :skip_digest => true) do
  - token = SecureRandom.hex(8)
  = content_tag(:tr, commit, :id => token, :class => ['narrow']) do
    %td
      %span.nobr= short_name_with_client(commit.project)
    %td
      = truncate(commit.reference_2, :length => 6)
    %td.tools.nobr
      = truncate(commit.description, :length => 25)

app/views/shared/_commit_one_line.html.haml
- cache("commit_one_line_#{commit.id}", :skip_digest => true) do
  - token = SecureRandom.hex(8)

  %tr.commit.one_line{ :id => token }
    %td= commit.try(:project).try(:client).try(:abbreviation)
    %td= truncate(commit.try(:project).try(:name), :length => 25)
    %td= truncate(commit.description, :length =>  30, :omission => '...')
    %td
      = truncate(commit.reference_2, :length => 10)
    %td
      %span.nobr= commit.time.to_datetime.to_s(:short_date)

app/views/shared/_pivotal_narrow.html.haml
- cache("pivotal_narrow_#{pivotal.id}", :skip_digest => true) do
  - token = SecureRandom.hex(8)
  = content_tag(:tr, pivotal, :id => token, :class => ['narrow']) do
    %td
      %span.nobr= short_name_with_client(pivotal.project)
    %td
      = truncate(pivotal.reference_1, :length => 10)
    %td.tools.nobr
      = truncate(pivotal.reference_2, :length => 15)

app/views/shared/_pivotal_one_line.html.haml
- cache("pivotal_one_line_#{pivotal.id}", :skip_digest => true) do
  - token = SecureRandom.hex(8)

  %tr.pivotal.one_line{ :id => token }
    %td= pivotal.try(:project).try(:client).try(:abbreviation)
    %td= truncate(pivotal.try(:project).try(:name), :length => 25)
    %td= truncate(pivotal.description, :length =>  40, :omission => '...')
    %td
      %span.nobr= pivotal.time.to_datetime.to_s(:short_date)

app/views/shared/_project_flat.haml
= content_tag(:li, project, :class => "project-entry") do
  .project_name
    %span.nobr= switch_to_project_link(project, short_name_with_client(project), "recent_")
  .tools
    - if project.clockable?
      = clock_in_widget(project, :icon)

app/views/shared/_project_picker.html.haml
= cache("project_picker", :skip_digest => true) do
  = page_block("Projects", :id => 'project_picker') do
    .project_picker
      = list_tree('home/project_node', 'home/project_list', Project.root.descendants)

app/views/shared/_recent_commits.html.haml
= page_block("Recent Commits", :id => "recent_commits") do
  %table.listing
    %tr
      %th Project
      %th Branch
      %th Message
    = render :partial => "shared/commit_narrow", :collection => current_user.reload.recent_commits, :as => :commit

app/views/shared/_recent_projects.html.haml
= page_block("Recent Projects", :id => "recent_projects") do
  - cache("recent_projects_#{current_user.id}_#{current_user.work_units.most_recent(1).first.try(:start_time)}", :skip_digest => true) do
    .recent_projects
      %ul.project-list
        = render :partial => "shared/project_flat", :collection => current_user.reload.recent_projects, :as => :project

app/views/shared/_timeclock.html.haml
= page_block("Timeclock", :id => "timeclock") do
  - if clocked_in?
    %span#tasktime{ :style => 'display:none;' }= current_work_unit.start_time.strftime('%s')
    = form_for(current_work_unit, :url => clock_out_path, :html => {:method => :delete, :class => :edit_work_unit}) do |f|
      #description
        #project_name= short_name_with_client(current_work_unit.project)
        #billable
          = f.label :billable
          = f.check_box(:billable)
      #task_elapsed -:--:--
      = f.text_area :notes, :size => 30, :placeholder => "Notes"
      = link_to "(+ show override tools)", '#', :id => 'override_trigger'
      %br
      #overrides
        started:
        = current_work_unit.start_time.to_s(:short_datetime)
        = f.text_field :stop_time, :size => 15, :placeholder => "Stop Time"
        = f.text_field :hours, :size => 15, :placeholder => "Hours"
      = f.button "Clock Out", :type => :submit
  - else
    .text_content
      %h3 You are not clocked in.
      - if current_user.current_project && current_project.clockable?
        = clock_in_widget(current_user.current_project, nil, :class => :button)
      - else
        %p Please select a clockable project if you wish to clock in.

app/views/shared/_work_unit_narrow.haml
- cache("work_unit_narrow_#{work_unit.id}", :skip_digest => true) do
  - token = SecureRandom.hex(8)
  = work_unit_row_tag(work_unit, token, :narrow) do
    %td
      %span.work_unit_label.nobr= short_name_with_client(work_unit.project)
    %td.numeric
      = "%.2f" % work_unit.hours
    %td.tools.nobr
      = link_to 'Edit', edit_work_unit_path(work_unit), class: 'actions edit'
      = link_to 'Delete', work_unit_path(work_unit, :delete_id => token), :method => :delete, :data => { :confirm => "Are you sure?"}, class: 'actions delete'
  = work_unit_details_row_tag(token, :hidden) do
    %td{ colspan: 3 }
      %dl
        %dt Project:
        %dd= short_name_with_client(work_unit.project)

        %dt Notes:
        %dd= work_unit.notes

        %dt Hours:
        %dd= "%.2f" % work_unit.hours

        %dt Started:
        %dd= work_unit.start_time.to_s(:short_datetime)

        %dt Finished:
        %dd= work_unit.stop_time.to_s(:short_datetime)