config/routes.rb
TimePulse::Application.routes.draw do

  resources :invoices
  resources :bills
  resources :groups
  resources :permissions
  resources :work_units, :except => :index
  resources :clients
  resources :projects do
    resource :github_pull, :controller => 'github_pull', :only => [:create]
    resource :pivotal_pull, :controller => 'pivotal_pull', :only => [:create]
  end
  resources :rates, :only => :update

  resources :project_reports
  resources :invoice_reports, :only => :show

  resource :github, :only => [:create], :controller => 'github'
  resource :pivotal, :only => [:create], :controller => 'pivotal'
  resource :user_preferences, :only => [ :edit, :update ]

  # TODO: Reenable these once LAz is working
  # match '/forbid' => 'permissions#destroy', :as => :forbid, :via => delete
  # match '/permit' => 'permissions#create', :as => :permit, :via => post
  # match '/ungroup_user' => 'groups_users#destroy', :as => :ungroup_user, :via => delete
  # match '/group_user' => 'groups_users#create', :as => :group_user, :via => post

  devise_for :users, :controllers => {:registrations => 'users' }
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy", :as => :logout
    get "/users/new" => "users#new", :as => :new_user
    get "/users" => "users#index", :as => :users
    get "/users/:id" => "users#show", :as => :user
    get "/users/:id/edit" => "users#edit", :as => :edit_user
    patch "/users/:id" => "users#update", :as => :update_user
  end
  match '/fix_work_unit/:id' => 'work_unit_fixer#create', :as => :fix_work_unit, :via => :post
  match '/set_current_project/:id' => 'current_project#create', :as => :set_current_project, :via => :post
  match '/clock_in_on/:id' => 'clock_time#create', :as => :clock_in, :via => :post
  match '/clock_out' => 'clock_time#destroy', :as => :clock_out, :via => :delete

  root :to => 'home#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer(4)      not null, primary key
#  parent_id   :integer(4)
#  lft         :integer(4)
#  rgt         :integer(4)
#  client_id   :integer(4)
#  name        :string(255)     not null
#  account     :string(255)
#  description :text
#  clockable   :boolean(1)      default(FALSE), not null
#  created_at  :datetime
#  updated_at  :datetime
#  billable    :boolean(1)      default(TRUE)
#  flat_rate   :boolean(1)      default(FALSE)
#

require 'cascade'

class Project < ActiveRecord::Base

  include Cascade

  acts_as_nested_set
  belongs_to :client
  has_many :work_units
  has_many :activities
  # Rates added to sub-project will override parent project rates completely.
  # Users may see rates disappear from a child when adding rates specifically for a child.
  has_many :rates
  accepts_nested_attributes_for :rates, :allow_destroy => true, :reject_if => lambda { |attr| attr['name'].blank? || attr['amount'].to_i < 1  }

  scope :archived, lambda { where( :archived => true) }
  scope :unarchived, lambda { where( :archived => false) }
  # default_scope :joins => :client

  validates_presence_of :name
  cascades :account, :clockable, :github_url, :pivotal_id

  before_save :no_rates_for_children, :cascade_client

  def is_base_project?
    parent == root
  end

  def base_rates
    is_base_project? || parent.blank? ? rates : parent.base_rates
  end

  private

  def no_rates_for_children
    rates.clear if parent != root
  end

  def cascade_client
    if self.client_id.nil? and parent
      parent.self_and_ancestors.reverse.find do |a|
        self.client_id = a.client_id unless a.client_id.nil?
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_admin!

  # GET /projects
  def index
    @root_project = Project.root
  end

  # GET /projects/1
  def show
    @project = Project.find(params[:id])

    @active_users = User.active
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.rates.build
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @project.rates.build if @project.parent == Project.root
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project was successfully created.'
      expire_fragment "picker_node_#{@project.id}"
      expire_fragment "project_picker"
      redirect_to(@project)
    else
      @project.rates.build
      render :action => "new"
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      expire_fragment "picker_node_#{@project.id}"
      expire_fragment "project_picker"
      flash[:notice] = 'Project was successfully updated.'
      redirect_to :action => "index"
    else
      @project.rates.build
      render :action => "edit"
    end
  rescue ActiveRecord::ActiveRecordError
    flash[:error] = "Illegal self referential or circular parent assignment"
    redirect_to(@project)
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @id = params[:id]
    @project.destroy
    expire_fragment "project_picker"

    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js
    end
  end

  private

  def project_params
    params.
    require(:project).
    permit(:name,
      :account,
      :description,
      :clockable,
      :billable,
      :flat_rate,
      :archived,
      :github_url,
      :pivotal_id,
      {:rates_attributes => [:id, :name, :amount, :_destroy]},
      :client_id,
      :parent_id)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def parent_project_selector(form)
    form.select(:parent_id, project_options, { :include_blank => "" }, { :class => "project_selector"})
  end

  def  client_selector(form = nil)
    if form
      form.select(:client_id, client_selector_array, { :include_blank => "" })
    else
      if @client
        select_tag( :client_id, options_for_select(client_selector_array, @client.id), { :include_blank => "" })
      else
        select_tag( :client_id, options_for_select(client_selector_array), { :include_blank => "" })
      end
    end
  end

  def client_selector_array
    @client_array ||= Client.all.to_a.collect{ |c| [c.name, c.id] }
  end

  def project_name_with_client(project, short=false)
    return unless project
    String.new.tap do |str|
      str << "[#{project.client.abbreviation.try(:upcase)}] " unless project.client.nil?
      str << (short ? truncate(project.name, :length => 20, :omission => '...') : project.name)
    end.html_safe
  end

  def short_name_with_client(project)
    project_name_with_client(project, true)
  end

  def switch_to_project_link(project, link_name = nil, prefix = "")
     link_to(link_name.nil? ? project.name : link_name,
       set_current_project_path(:id => project.id),
       :method => :post,
       :id => prefix + "switch_to_" + dom_id(project)
     )
   end

  def clock_in_widget(project, style = nil, options = {})
    title = "Clock in on #{short_name_with_client(project)}"
    css_class = "clock_in_on_" + dom_id(project)
    if style == :icon
      link_to(image_tag('icons/clock_in.png', :alt => title), clock_in_path(:id => project),
              options.merge(:method => :post, :title => title, :class => css_class))
    else
      link_to(title, clock_in_path(:id => project),
              options.merge(:method => :post, :title => title, :class => css_class))
    end.html_safe
  end

  def expand_widget(project)
    cssid = "expand_" + dom_id(project)
    content_tag(:span, :class => "expand-widget", :id => cssid, :"data-target" => "##{dom_id(project)} > ul") do
      images = image_tag('icons/expand.png', :alt => "Expand", :class => "expand")
      images = images + image_tag('icons/collapse.png', :alt => "Collapse", :class => "collapse")
      images
    end
  end
end

app/views/projects/_active_project.html.haml
-if !node.archived
  = render :partial => "project", :locals => { :node => node, :depth => depth, :children => (children if defined? children) }

app/views/projects/_archived_project.html.haml
-if node.archived
  = render :partial => "project", :locals => { :node => node, :depth => depth, :children => ( children  if defined? children ) }

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  = f.error_messages

  %fieldset.general
    = f.labeled_input(:client_id){ client_selector(f) }
    = f.labeled_input(:parent_id){ parent_project_selector(f) }
    = f.labeled_input :name
    = f.labeled_input :account
    = f.labeled_input :description
    = f.labeled_input :github_url
    = f.labeled_input :pivotal_id, :text => "Pivotal Project ID", :comment => "(number at the end of URL for project)"
    = f.labeled_input(:clockable){ f.check_box(:clockable) }
    = f.labeled_input(:billable){ f.check_box(:billable)  }
    = f.labeled_input(:flat_rate){ f.check_box(:flat_rate) }
    = f.labeled_input(:archived){ f.check_box(:archived) }

  - if @project.new_record? || @project.is_base_project?
    %fieldset.rates.hide-initially
      %legend Rates

      %table
        %thead
          %tr
            %th Name
            %th Amount
            - unless action_name == 'new'
              %th.actions Remove
        %tfoot
          %tr
            %td{ :colspan => action_name == 'new' ? 2 : 3 }
              %a.add-rate{ :href => '#' } Add Rate
        %tbody
          = f.fields_for :rates do |ff|
            %tr
              %td= ff.text_field :name, :class => 'rate-name-field', :placeholder => 'e.g. \'Engineer\''
              %td= ff.text_field :amount, :class => 'rate-amount-field', :placeholder => 'e.g. \'100\''
              - unless action_name == 'new'
                %td.actions
                  - if ff.object.persisted?
                    = ff.check_box :_destroy
                    = ff.label :_destroy, 'Remove'

  = f.unlabeled_submit 'Submit'

app/views/projects/_project.html.haml
= content_tag_for(:tr, node) do
  %td
    = depth_indicator(depth)
    = "#{node.name}"

  %td= node.client.nil? ? "" : node.client.name
  %td= node.description
  %td
    = link_to_if_admin_authorized 'Show', node, class: 'actions show'
    = link_to_if_admin_authorized 'Edit', edit_project_path(node), class: 'actions edit'
    = link_to_if_admin_authorized 'Destroy', node, data: { confirm: 'Are you sure?' }, :method => :delete, class: 'actions delete'
- if defined? children
  = children

app/views/projects/_project_header.html.haml
%tr
  %th Project
  %th Client
  %th Description
  %th

app/views/projects/destroy.js.erb
$("#project_<%= @id %>").remove()

app/views/projects/edit.html.haml
- set_headline "Editing Project #{@project.name}"

.button-wrap
  = link_to 'Back', projects_path, class: 'button radius'

= render :partial => 'form'

app/views/projects/index.html.haml
- set_headline  "Listing Projects"
/ **** tabbed table here
.button-wrap
  = link_to 'New Project', new_project_path, class: 'button radius'

= tabbed_panel do |tp|
  = tp.add_tab("Active") do
    %table.listing
      = render :partial => "project_header"
      = list_tree('active_project', 'home/project_list', @root_project.descendants)

  = tp.add_tab("Archived") do
    %table.listing
      = render :partial => "project_header"
      = list_tree('archived_project', 'home/project_list', @root_project.descendants)

app/views/projects/new.html.haml
- set_headline "New Project"

.button-wrap
  = link_to 'Back to List', projects_path, class: 'button radius'

= render :partial => 'form'

app/views/projects/show.html.haml
- set_headline "Project Info: #{@project.name}"

.button-wrap
  = link_to 'Edit', edit_project_path(@project), class: 'button radius'
  = link_to 'Back to List', projects_path, class: 'button radius'

.general
  %p
    %strong Name:
    %br
    =h @project.name

  %p
    %strong Account:
    %br
    =h @project.account

  %p
    %strong Description:
    %br
    =h @project.description

  %p
    %strong Github URL:
    %br
    =h @project.github_url

  %p
    %strong Pivotal Project ID:
    %br
    =h @project.pivotal_id

  %p
    = link_to 'Pull Commit History', project_github_pull_path(:project_id => @project), :method => :post
  %p
    = link_to 'Pull Pivotal Stories', project_pivotal_pull_path(:project_id => @project), :method => :post

.rates
  - rates = @project.base_rates
  - if rates.empty?
    %p
      %strong Rates
      %br
      None
  - else
    %table.rates
      %caption Rates
      %thead
        %tr
          %th Name
          %th Amount
          %th Members
      %tbody
        - rates.each do |rate|
          %tr
            %td #{h rate.name}
            %td #{h rate.amount}
            %td
              - if @project.is_base_project?
                = form_for rate, :method => :put, :html => {:class => 'rates-users-container hide-initially'} do |f|
                  = select_tag :users, options_for_rates_users(rate), :multiple => true
                  = f.submit 'Update'
              - else
                = rate.users.map { |user| user.name }.join ', '